version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8085:80"
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
